In [1]:
import numpy as np

In [2]:
nodes = [[0, 0], [1, 0], [0, 1]]

def shape_func(coords):
    
    n_1 = 1 - xi - eta
    n_2 = xi
    n_3 = eta
    n = np.array([[n_1, 0, n_2, 0, n_3, 0], [0, n_1, 0, n_2, 0, n_3]])
    
    return n

In [3]:
shape_func(0, 0)

array([[1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0]])

In [10]:
def shape_func(coord, el_coords):
    a_1 = el_coords[1][0]*el_coords[2][1] - el_coords[2][0]*el_coords[1][1] 
    a_2 = el_coords[2][0]*el_coords[0][1] - el_coords[0][0]*el_coords[2][1] 
    a_3 = el_coords[0][0]*el_coords[1][1] - el_coords[1][0]*el_coords[0][1] 

    b_1 = el_coords[1][1] - el_coords[2][1]
    b_2 = el_coords[2][1] - el_coords[0][1]
    b_3 = el_coords[0][1] - el_coords[1][1]

    c_1 = el_coords[2][0] - el_coords[1][0]
    c_2 = el_coords[0][0] - el_coords[2][0]
    c_3 = el_coords[1][0] - el_coords[0][0]

    delta = (el_coords[0][0]*b_1 + el_coords[1][0]*b_2 + el_coords[2][0]*b_3) / 2
    
    n_1 = 1/(2*delta) * (a_1 + b_1*coord[0] + c_1*coord[1])
    n_2 = 1/(2*delta) * (a_2 + b_2*coord[0] + c_2*coord[1])
    n_3 = 1/(2*delta) * (a_3 + b_3*coord[0] + c_3*coord[1])
    
    n = np.array([
        [n_1, 0, n_2, 0, n_3, 0],
        [0, n_1, 0, n_2, 0, n_3]
    ])
    
    return n
    

el_coords = np.array([[0, 0], [1, 0], [0, 1]])
x = [1/2, 1/2]

shape_func(x, el_coords)

array([[0. , 0. , 0.5, 0. , 0.5, 0. ],
       [0. , 0. , 0. , 0.5, 0. , 0.5]])

In [35]:
el_coords = np.array([[10, 0], [15, 4], [5, 12]])
x = [15, 2]

n = shape_func(x, el_coords)

a = np.array([
    [1], 
    [0], 
    [0], 
    [0], 
    [0], 
    [0]
])

n.dot(a)
# n

array([[0.25],
       [0.  ]])